---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: paiement-app
  namespace: default
  labels:
    app: paiement-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paiement-app
  template:
    metadata:
      labels:
        app: paiement-app
    spec:
      containers:
      - name: paiement-app
        image: "enoch180/paiement:1.0"
        ports:
          - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: paiement-app
  namespace: default
spec:
  selector:
    app: paiement-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 4003
    port: 83
